#メッセージのカスタマイズ 色変更のみ
messageCustom: false

discord:
      enable: false #Discord連携の有効化
      token: "YOUR_DISCORD_BOT_TOKEN" #DiscordBotのTokenを入力
      discord_servers: #必要に応じて追加
        - server_name: "Discordサーバー1"
          channel_id: "123456789012345678"  # Discord サーバー1のチャンネルID
        - server_name: "Discordサーバー2"
          channel_id: "234567890123456789"  # Discord サーバー2のチャンネルID
        - server_name: "Discordサーバー3"
          channel_id: "345678901234567890"  # Discord サーバー3のチャンネルID
# サーバー名の配列
#必要に応じて追加
servers:
  - server1
  - server2
  - server3